connector.name=iceberg
# Loại catalog: Dùng Hive Metastore (Chuẩn Enterprise)
iceberg.catalog.type=hive_metastore

# Địa chỉ của con server vừa dựng ở bước 1
hive.metastore.uri=thrift://hive-metastore:9083

# --- CẤU HÌNH MINIO (S3) ---
fs.native-s3.enabled=true
s3.endpoint=http://minio:9000
s3.region=us-east-1
s3.path-style-access=true
s3.aws-access-key=minio
s3.aws-secret-key=minio123
#s3.ssl.enabled=false

# Quan trọng: Cho phép Trino ghi đè file (nếu cần)
iceberg.file-format=PARQUET
iceberg.register-table-procedure.enabled=true
